# Generated by Django 4.2.5 on 2023-09-11 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PersonName",
            new_name="PersonDetail",
        ),
    ]
