# Generated by Django 4.2.5 on 2023-09-11 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0002_rename_personname_persondetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persondetail",
            name="age",
        ),
        migrations.RemoveField(
            model_name="persondetail",
            name="created",
        ),
        migrations.RemoveField(
            model_name="persondetail",
            name="email",
        ),
        migrations.RemoveField(
            model_name="persondetail",
            name="userid",
        ),
    ]
